:sparkles: Add text to README
FakeHaacked/best-example pull request #6
Opened 2019-01-16 19:30 UTC by Haacked

This PR adds some text to the `README.md` file.

## More Details
This is the best pull request to the best example ever because:

1. It is descriptive.
2. It is short.
3. It is sweet.

2019-01-16 20:10 UTC, Haacked commented
The reason we’re embarking on this work is duet to compliance reasons.
<details>
## More Details
I don’t want to bore everyone with all the nitty gritty details, but foro those whoo are interested, keep on reading…
</details>

2019-01-16 20:27 UTC, haacked commented
<img width="1680" alt="9781119572671 fg0806" src="https://user-images.githubusercontent.com/19977/51276613-00233780-198a-11e9-8f26-cf3bdfe8a109.png">

2019-01-19 22:34 UTC, FakeHaacked requested changes
I like the direction this is heading. I did not find any glaring errors or omissions.

I did add one open question and suggest a change. I wanted to hear your feedback on those suggestions before I approved the pull request. It's not necessary that you take the suggestions.

2019-01-19 22:34 UTC, FakeHaacked commented on README.md
>  # The Best Example Ever
🤔 Seems a bit _superlative_, no? Will the audience agree with this?

@sarah-wecan, any thoughts on this?

2019-01-19 22:34 UTC, FakeHaacked commented on README.md
> +## Installation
```suggestion
## Installation Instructions
```
Let's be more explicit about what this section is.

2025-01-16 18:27 UTC, closed without merging